[package]
name = "Rust1090"
version = "1.0.0"
edition = "2021"

[dependencies]
couch_rs = "0.12.0"
dotenv = "0.15.0"
geo = "0.29.3"
reqwest = "0.12.12"
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
warp = "0.3.7"

